cogset/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from cogset.models import Quiz, Question, Response

urlpatterns = patterns('',
	#ex: /quizzes/
	url(r'^$',
		ListView.as_view(
			queryset = Quiz.objects.order_by('-pub_date')[:5],
			context_object_name = 'latest_quiz_list',
			template_name = 'quizzes/index.html'),
		name='index'),
	#ex: /quizzes/5
	url(r'^(?P<pk>\d+)/$',
		DetailView.as_view(
			model=Quiz,
			template_name='quizzes/detail.html'),
		name='detail'),
	# ex: /quizzes/question/5
	url(r'^question/(?P<pk>\d+)/$',
		DetailView.as_view(
			model=Question,
			template_name='quizzes/question.html'),
		name='question'),
	# handles form response
	url(r'^respond/(?P<question_id>\d+)$', 'cogset.views.respond', name='respond'),
	# ex: quizzes/results/5
	url(r'^results/(?P<pk>\d+)$',
		DetailView.as_view(
			model=Response,
			template_name='quizzes/results.html'),
		name='results'),
)

headlamp/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from headlamp.models import Presentation, Slide, SlideSegment

urlpatterns = patterns('',
	# /headlamp/ or /presentations/
	url(r'^$',
		ListView.as_view(
			queryset = Presentation.objects.order_by('lesson','title')[:5],
			context_object_name = 'presentation_list',
			template_name = 'presentations/index.html'),
		name='index'),
	# /headlamp/4/show or /presentations/4/show
	url(r'^(?P<presentation_id>\d+)/show$', 'headlamp.views.show', name='show'),
)

ieltsonabike/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^cogset/', include('cogset.urls')),
    url(r'^quizzes/', include('cogset.urls', namespace="quizzes")),
    url(r'^presentations/', include('headlamp.urls', namespace="presentations")),
    
    # Examples:
	# url(r'^$', 'ieltsonabike.views.home', name='home'),
    # url(r'^ieltsonabike/', include('ieltsonabike.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # CKEditor URL for rich text fields
    (r'^ckeditor/', include('ckeditor.urls')),
    
)

# Debug Media File Server
if settings.DEBUG:
# static files (images, css, javascript, etc.)
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.MEDIA_ROOT}))

cogset/models.py
from django.db import models
from django.contrib.auth.models import User

class Quiz(models.Model):
	PUB_STATUS = ( 
		 ('D', 'draft'), # unfinished draft
		 ('P', 'publish'), # published, finished
		 ('T', 'trash'), # deleted
	)
	
	title = models.CharField(max_length=200)
	pub_status= models.CharField(max_length=1, choices=PUB_STATUS)
	pub_date = models.DateTimeField('date published')
	feedback = models.TextField(blank=True, default="")  # to provide user some post quiz comment 
	
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural = "Quizzes"

class Question(models.Model):
	title = models.CharField(max_length=200)
	hint = models.CharField(max_length=200, blank=True, default="")
	quiz = models.ForeignKey(Quiz)
	
	def __unicode__(self):
		return self.title

class Answer(models.Model):
	title = models.CharField(max_length=200)
	question = models.ForeignKey(Question)
	feedback = models.TextField(blank=True, default="") # to provide user some comment on his answer
	score = models.DecimalField(max_digits=2, decimal_places=1) # full score is 1, half in 0.5, etc
	is_correct = models.BooleanField()
	
	def __unicode__(self):
		return self.title
	
	class Meta:
		order_with_respect_to = 'question' # uses get/set_answer_order() methods

	def score_as_percentage(self):
		return "{0:.0f}%".format(self.score*100)
	
#	def _order_as_int(self): # outputs as integer the long _order value created by order_wrt
#		return int(self._order)
#		
#	position = property(_order_as_int) # position property for grappelli
		
class Response(models.Model):
	user = models.ForeignKey(User)
	question = models.ForeignKey(Question)
	answer = models.ForeignKey(Answer)
	
	def __unicode__(self):
		return u"response id %s from user %s" % (str(self.id), self.user.username)
	
	def _score(self):
		return self.answer.score
			
	score = property(_score)

cyclocomputer/models.py
from django.db import models
from ckeditor.fields import RichTextField
from cogset.models import Quiz
from headlamp.models import Presentation

class Lesson(models.Model):	
	title = models.CharField(max_length=200)
	quiz = models.ForeignKey(Quiz)
	presentation = models.OneToOneField(Presentation)
	courses = models.ManyToManyField('Course')
	
	IMPORTANCE = ( (1, 'optional'),  (2, 'normal'), (3, 'essential') )
	importance = models.SmallIntegerField(choices=IMPORTANCE,default=2)
	
	def __unicode__(self):
		return self.title

class Resource(models.Model):
	title = models.CharField(max_length=200)
	description = RichTextField()
	
	def __unicode__(self):
		return self.title	
		
	class Meta:
		abstract = True
		
class FileResource(Resource):
	file = models.FileField(upload_to='resources', null=True, blank=True)
	lessons = models.ManyToManyField(Lesson)
	
class LinkResource(Resource):	
	link = models.URLField(max_length=200)
	lessons = models.ManyToManyField(Lesson)

class Course(models.Model): # Allows lessons to be part of one or more courses; ex. Academic
	title = models.CharField(max_length=200)
	slug = models.SlugField()
	
	def __unicode__(self):
		return self.slug

	

headlamp/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Presentation(models.Model):
	title = models.CharField(max_length=200)
	audio = models.FileField(upload_to='audio', null=True, blank=True)
	
	def __unicode__(self):
		return self.title	
		
class Slide(models.Model):
	title = models.CharField(max_length=200)
	header = RichTextField(blank=True)
	footer = RichTextField(blank=True)
	presentation = models.ForeignKey(Presentation)
	slide_number = models.IntegerField()
	#style = models.ForeignKey(SlideStyle)
	
	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ['slide_number']
		unique_together = (('presentation', 'slide_number'),)
	
class SlideSegment(models.Model):
	slide = models.ForeignKey(Slide)
	duration = models.IntegerField() # duration of slide segment in ms
	position = models.SmallIntegerField() # to order segments
	content = RichTextField(blank=True)
	subtitle = models.TextField(blank=True)

	def start_time (self): # cumulative elapsed time of other preceding segments
		previous_segments = SlideSegment.objects.filter(
			slide__presentation = self.slide.presentation #returns all segments in this presentation
		).exclude(
			slide__slide_number__gt = self.slide.slide_number #exclude later slides
		).exclude(
			slide = self.slide, position__gte = self.position #exclude later segments
		)
		return previous_segments.aggregate(models.Sum('duration'))['duration__sum'] #output sum duration values of all returned objects
	
	def __unicode__(self):
		return u"Slide %s Segment %s" % (str(self.slide.slide_number), str(self.position))

	class Meta:
		ordering = ['position']
		unique_together = (('slide', 'position'),)

#class SlideStyle(models.Model):
#	name = Charfield()
#	css = 

cogset/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from cogset.models import Quiz, Question, Answer, Response
    
def respond(request, question_id): # processes submitted answer 
	q = get_object_or_404(Question, pk=question_id)
	try:
		selected_answer = q.answer_set.get(pk=request.POST['answer'])
	except (KeyError, Answer.DoesNotExist):
		# Redisplay the question form.
		return render(request, 'quizzes/question.html', {
			'question': q,
			'error_message': "You didn't select an answer.",
    })
	else:
		# answer is submitted so a response object is created and saved
		r = Response(user=request.user, question=q, answer=selected_answer)
		r.save()
		return HttpResponseRedirect(reverse('quizzes:results', args=(r.id,)))
        
def results(request, response_id):
    response = get_object_or_404(Response, pk=response_id)
    return render(request, 'quizzes/results.html', {'response': response})

cyclocomputer/views.py
# Create your views here.

headlamp/views.py
from django.shortcuts import render, get_object_or_404
from headlamp.models import Presentation

def show(request, presentation_id):
	presentation = get_object_or_404(Presentation, pk=presentation_id)
	return render(request, 'presentations/show.html', {'presentation': presentation})

cogset/templates/quizzes/detail.html
<h1>{{ quiz }}</h1>
<ul>
{% for question in quiz.question_set.all %}
	<li><a href="{% url 'quizzes:question' question.id %}">{{ question }}</a></li>
{% endfor %}
</ul>

cogset/templates/quizzes/index.html
{% extends "base.html" %}

{% block content %}
{% if latest_quiz_list %}
	<ul>
	{% for quiz in latest_quiz_list %}
		<li><a href="{% url 'quizzes:detail' quiz.id %}">{{ quiz.title }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No quizzes are available.</p>
{% endif %}
{% endblock %}

cogset/templates/quizzes/question.html
<h1>{{ question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quizzes:respond' question.id %}" method="post">
{% csrf_token %} <!-- to prevent cross site request forgeries -->
{% for answer in question.answer_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}">{{ answer }}</label><br />
{% endfor %}
<input type="submit" value="Submit" />
</form>

cogset/templates/quizzes/results.html
<h1>{{ response.question }}</h1>

{% if response.answer.is_correct %}
	<p><strong>Correct!</strong></p>
{% else %}
	<p><strong>Wrong!</strong></p>
{% endif %}

<p>You receive a score of {{ response.answer.score_as_percentage }} </p>
{# <p><a href="{% url 'quizzes:question' response.question.id %}">Try again?</a></p> #}

headlamp/templates/presentations/base_presentations.html
{% extends "base.html" %}

{% block pagetitle %} {{ title|default:"Presentation" }} {% endblock pagetitle %}

headlamp/templates/presentations/index.html
{% extends "presentations/base_presentations.html" %}

{% block content %}
{% if presentation_list %}
	<ul>
	{% for presentation in presentation_list %}
		<li><a href="{% url 'presentations:show' presentation.id %}">{{ presentation.title }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No presentations are available.</p>
{% endif %}
{% endblock %}

headlamp/templates/presentations/show.html
{% extends "presentations/base_presentations.html" %}

{% load staticfiles %}

{% block css %} {{ block.super }}
	<link rel="stylesheet" href="{% static 'presentations/css/deck.core.css' %}">
	<link rel="stylesheet" href="{% static 'presentations/css/web-2.0.css' %}">
	<link rel="stylesheet" href="{% static 'presentations/css/horizontal-slide.css' %}">
	<link rel="stylesheet" href="{% static 'presentations/css/deck.scale.css' %}">
	<link rel="stylesheet" href="{% static 'presentations/css/presentation-styles.css' %}">
	<link rel="stylesheet" href="{% static 'presentations/skin/jplayer.blue.monday.css' %}">
{% endblock css %}

{% block js %} {{ block.super }}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="{% static 'presentations/js/modernizr.custom.js' %}"></script>
	<script src="{% static 'presentations/js/deck.core.js' %}"></script>
	<script src="{% static 'presentations/js/deck.automatic.js' %}"></script>
	<script src="{% static 'presentations/js/deck.scale.js' %}"></script>
	<script src="{% static 'presentations/js/jquery.jplayer.min.js' %}"></script>
{% endblock js %}

{% block content %}

{% if presentation %}
{% autoescape off %}
<div id="slideshow">
  <div class="deck-container deck-scale">
  <section class ="slide" id="presentation_title">
  	<h2>{{ presentation }}</h2>
  </section>
  {% for slide in presentation.slide_set.all %}
  	<section class="slide" id="slide{{ forloop.counter }}">
  		<h2 id="slideheadline{{ forloop.counter }}">{{ slide.title|title }}</h2>
  			{% for slidesegment in slide.slidesegment_set.all %}
  			<div class="slide" id="slide{{forloop.parentloop.counter}}segment{{forloop.counter}}" data-duration="{{slidesegment.duration}}">{{ slidesegment.content|removetags:"p" }}</div>
  			{% endfor %}
  	</section>
  {% endfor %}
  </div>
</div> 
{% endautoescape %}

<div id="mediaplayer">
<!-- Begin Jplayer code --> 
  <div id="jquery_jplayer_1" class="jp-jplayer"></div>
  <div id="jp_container_1" class="jp-audio">
    <div class="jp-type-single">
      <div class="jp-gui jp-interface">
        <ul class="jp-controls">
          <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
          <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
          <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
          <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
          <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
          <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
        </ul>
        <div class="jp-progress">
          <div class="jp-seek-bar">
            <div class="jp-play-bar"></div>
          </div>
        </div>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
        <div class="jp-time-holder">
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
          <ul class="jp-toggles">
            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
          </ul>
        </div>
      </div>
 <!-- <div class="jp-title">
        <ul>
          <li>Bubble</li>
        </ul>
      </div> -->
      <div class="jp-no-solution">
        <span>Update Required</span>
        To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
      </div>
    </div>
  </div>
  <!-- End Jplayer code --> 
</div>

{% else %}
	<p>No slides are available.</p>
{% endif %}

{% endblock content %}

{% block bottomjs %} {{ block.super }}
<script>
$(function() {
 	$.extend(true, $.deck.defaults, {
 		classes: {
	    	scale: 'deck-scale'
	   	},

	   	keys: {
	    	scale: 83 // s
		},

		baseHeight: null,
		scaleDebounce: 200,
	});
	$.extend(true, $.deck.defaults, {
		automatic: {
    		startRunning: false,
    		cycle: false,
    		slideDuration: 1000,
		},
	});
	$.deck('.slide');
});

$("#container_button").click(function() {
	$.deck('play');
});
</script>

<!-- Begin JPlayer Code -->
<script type="text/javascript">
    $(document).ready(function(){
      $("#jquery_jplayer_1").jPlayer({
        ready: function () {
          $(this).jPlayer("setMedia", {
            mp3: "{{ presentation.audio.url }}"
          });
        },
        swfPath: "{% static 'presentations/other/' %}js",
        supplied: "mp3"
      });
      // on audio play, start slideshow
      $("#jquery_jplayer_1").bind($.jPlayer.event.play, function() {
        $.deck('play')
      });
       // on audio play, start slideshow
      $("#jquery_jplayer_1").bind($.jPlayer.event.pause, function() {
        $.deck('pause')
      });
    });
  </script>
  <!-- End JPlayer Code -->
{% endblock bottomjs %}

templates/base.html
<!DOCTYPE html>
{% load sitetree %}
{% load staticfiles %}
<head>
{% block css %}
	<link rel="stylesheet" href="{% static 'site/css/responsive-nav.css' %}">
{% endblock css %}
{% block js %}
	<script src="{% static 'site/js/responsive-nav.min.js' %}"></script>
{% endblock js %}	
	<title>{% block pagetitle %} IELTS on a Bike {% endblock pagetitle %}</title>
</head>

<body>
{% block nav %}	
	<div id="nav">
		{% sitetree_menu from "maintree" include "trunk,topmenu" %}
	</div>
{% endblock nav %}

{% block content %} {% endblock content%}

{% block bottomjs %}
<script>
  var navigation = responsiveNav("#nav");
</script>
{% endblock bottomjs %}
</body>
</html>